import {
  StudentProfile,
  SubjectCourse,
  TimetableBlock,
  StudyTask,
  HealthLog,
  StudentBadge,
  StudySquad,
  MotivationInsight,
} from '../types';

export const initialProfile: StudentProfile = {
  name: 'Alex Rivera',
  major: 'Computer Science & Cognitive Science',
  semester: 'Semester 4 (Spring 2026)',
  chronotype: 'balanced',
  peakFocusStart: '09:00',
  peakFocusEnd: '13:30',
  targetStudyHoursDaily: 5.5,
  targetSleepHoursDaily: 8.0,
  targetWaterMlDaily: 2500,
};

export const initialSubjects: SubjectCourse[] = [
  {
    id: 'sub-1',
    name: 'Data Structures & Algorithms',
    code: 'CS 210',
    color: '#3B82F6', // blue
    difficulty: 'challenging',
    weeklyGoalHours: 10,
    loggedMinutesThisWeek: 420,
    nextExamDate: '2026-04-12',
  },
  {
    id: 'sub-2',
    name: 'Cognitive Neuroscience',
    code: 'COG 105',
    color: '#8B5CF6', // purple
    difficulty: 'moderate',
    weeklyGoalHours: 6,
    loggedMinutesThisWeek: 260,
    nextExamDate: '2026-04-18',
  },
  {
    id: 'sub-3',
    name: 'Linear Algebra & Applications',
    code: 'MATH 220',
    color: '#10B981', // emerald
    difficulty: 'challenging',
    weeklyGoalHours: 8,
    loggedMinutesThisWeek: 310,
    nextExamDate: '2026-04-05',
  },
  {
    id: 'sub-4',
    name: 'Technical Writing & Ethics',
    code: 'ENG 180',
    color: '#F59E0B', // amber
    difficulty: 'easy',
    weeklyGoalHours: 4,
    loggedMinutesThisWeek: 180,
    nextExamDate: '2026-04-25',
  },
];

export const initialTimetable: TimetableBlock[] = [
  {
    id: 'tb-1',
    title: 'Morning Energizer & Mindful Breakfast',
    type: 'meal',
    startTime: '07:30',
    endTime: '08:15',
    durationMinutes: 45,
    completed: true,
    priority: 'medium',
    notes: 'Hydrate 500ml water, oatmeal, brief morning sunlight',
    energyRequirement: 'low',
  },
  {
    id: 'tb-2',
    title: 'Deep Work: Dynamic Programming Problem Sets',
    type: 'study',
    startTime: '08:30',
    endTime: '10:00',
    durationMinutes: 90,
    subjectId: 'sub-1',
    subjectName: 'CS 210',
    completed: true,
    priority: 'high',
    notes: 'Focus on Memoization vs Tabulation on LeetCode Mediums',
    energyRequirement: 'high',
    isAiGenerated: true,
  },
  {
    id: 'tb-3',
    title: 'Hydration & 10-Min Eye Stretch Break',
    type: 'break',
    startTime: '10:00',
    endTime: '10:15',
    durationMinutes: 15,
    completed: true,
    priority: 'low',
    notes: '20-20-20 rule, drink 300ml water, wrist stretches',
    energyRequirement: 'low',
  },
  {
    id: 'tb-4',
    title: 'Lecture: Memory Consolidation in the Hippocampus',
    type: 'class',
    startTime: '10:30',
    endTime: '12:00',
    durationMinutes: 90,
    subjectId: 'sub-2',
    subjectName: 'COG 105',
    location: 'Science Hall 302',
    completed: true,
    priority: 'high',
    energyRequirement: 'medium',
  },
  {
    id: 'tb-5',
    title: 'Nutritious Campus Lunch & Social Walk',
    type: 'meal',
    startTime: '12:15',
    endTime: '13:15',
    durationMinutes: 60,
    completed: false,
    priority: 'medium',
    notes: 'Grilled protein bowl + water refill at Student Commons',
    energyRequirement: 'low',
  },
  {
    id: 'tb-6',
    title: 'Problem Session: Eigenvectors & Matrix Diagonalization',
    type: 'study',
    startTime: '13:30',
    endTime: '15:00',
    durationMinutes: 90,
    subjectId: 'sub-3',
    subjectName: 'MATH 220',
    location: 'Main Library 4th Floor Quiet Zone',
    completed: false,
    priority: 'high',
    notes: 'Work through textbook chapter 5 exercises 12-24',
    energyRequirement: 'high',
    isAiGenerated: true,
  },
  {
    id: 'tb-7',
    title: 'Campus Gym Session & Aerobic Reset',
    type: 'health',
    startTime: '15:30',
    endTime: '16:30',
    durationMinutes: 60,
    location: 'Recreation Center',
    completed: false,
    priority: 'medium',
    notes: 'Cardio + shoulder flexibility to relieve study posture tension',
    energyRequirement: 'medium',
  },
  {
    id: 'tb-8',
    title: 'Study Squad Sync: Algorithm Practice Sprint',
    type: 'study',
    startTime: '17:00',
    endTime: '18:15',
    durationMinutes: 75,
    subjectId: 'sub-1',
    subjectName: 'CS 210',
    location: 'Online Squad Room (CS Algorithm Crunchers)',
    completed: false,
    priority: 'medium',
    notes: 'Review Graph Traversal mock questions with Maya & Liam',
    energyRequirement: 'medium',
  },
  {
    id: 'tb-9',
    title: 'Dinner & Screen-free Wind Down',
    type: 'personal',
    startTime: '19:00',
    endTime: '20:30',
    durationMinutes: 90,
    completed: false,
    priority: 'low',
    notes: 'Warm tea, call family, review tomorrow timetable overview',
    energyRequirement: 'low',
  },
];

export const initialTasks: StudyTask[] = [
  {
    id: 'tsk-1',
    title: 'Implement Dijkstra & Bellman-Ford in C++',
    subjectId: 'sub-1',
    subjectCode: 'CS 210',
    type: 'assignment',
    dueDate: '2026-03-24',
    estimatedMinutes: 180,
    completedMinutes: 90,
    status: 'in_progress',
    priority: 'urgent',
    tags: ['Coding', 'Graphs', 'Project 3'],
  },
  {
    id: 'tsk-2',
    title: 'Read Kandel Ch 14: Long-Term Potentiation',
    subjectId: 'sub-2',
    subjectCode: 'COG 105',
    type: 'reading',
    dueDate: '2026-03-25',
    estimatedMinutes: 60,
    completedMinutes: 0,
    status: 'todo',
    priority: 'medium',
    tags: ['Neuroplasticity', 'Spaced Repetition'],
  },
  {
    id: 'tsk-3',
    title: 'Eigenvalue Proofs Problem Set 6',
    subjectId: 'sub-3',
    subjectCode: 'MATH 220',
    type: 'assignment',
    dueDate: '2026-03-27',
    estimatedMinutes: 120,
    completedMinutes: 45,
    status: 'in_progress',
    priority: 'high',
    tags: ['Math Lab', 'Proof Writing'],
  },
  {
    id: 'tsk-4',
    title: 'Draft Essay on AI Alignment & Ethical Dilemmas',
    subjectId: 'sub-4',
    subjectCode: 'ENG 180',
    type: 'assignment',
    dueDate: '2026-03-30',
    estimatedMinutes: 150,
    completedMinutes: 0,
    status: 'todo',
    priority: 'medium',
    tags: ['Term Paper', 'Draft 1'],
  },
  {
    id: 'tsk-5',
    title: 'Anki Flashcard Revision: Graph Algorithms',
    subjectId: 'sub-1',
    subjectCode: 'CS 210',
    type: 'revision',
    dueDate: '2026-03-23',
    estimatedMinutes: 30,
    completedMinutes: 30,
    status: 'done',
    priority: 'normal',
    tags: ['Spaced Repetition', 'Quick Review'],
  },
];

export const initialHealthLog: HealthLog = {
  date: '2026-03-23',
  waterIntakeMl: 1750,
  targetWaterMl: 2500,
  sleepHours: 7.5,
  sleepQuality: 4,
  bedtime: '23:30',
  wakeTime: '07:00',
  mealsLogged: {
    breakfast: true,
    lunch: true,
    dinner: false,
    healthySnack: true,
  },
  screenBreaksTaken: 4,
  targetScreenBreaks: 6,
  physicalActivityMinutes: 35,
  stressLevel: 2,
  mood: 'focused',
  reflectionNote: 'Feeling clear-headed after morning algorithms session. Ready for math in the afternoon!',
};

export const initialBadges: StudentBadge[] = [
  {
    id: 'bdg-1',
    name: 'Hydration Hero',
    description: 'Hit 2,500ml water goal 3 days in a row',
    icon: 'Droplet',
    category: 'health',
    unlockedAt: '2026-03-21',
  },
  {
    id: 'bdg-2',
    name: 'Deep Focus Titan',
    description: 'Completed 4+ Pomodoro focus sessions in a single day',
    icon: 'Flame',
    category: 'focus',
    unlockedAt: '2026-03-22',
  },
  {
    id: 'bdg-3',
    name: 'Early Bird Lark',
    description: 'Began primary study block before 9:00 AM',
    icon: 'Sun',
    category: 'consistency',
    unlockedAt: '2026-03-23',
  },
  {
    id: 'bdg-4',
    name: 'Study Squad Catalyst',
    description: 'Coordinated a group task and sent peer cheers',
    icon: 'Users',
    category: 'squad',
    unlockedAt: '2026-03-20',
  },
  {
    id: 'bdg-5',
    name: 'Burnout Shield',
    description: 'Maintained 7.5+ hrs sleep during an exam prep week',
    icon: 'ShieldCheck',
    category: 'health',
  },
  {
    id: 'bdg-6',
    name: '7-Day Scholar Streak',
    description: 'Consistently logged academic and wellness habits for 7 days',
    icon: 'Award',
    category: 'consistency',
  },
];

export const initialMotivationInsight: MotivationInsight = {
  title: 'Peak Energy Capitalization',
  quote: '“Success is the sum of small efforts, repeated day in and day out.” — Robert Collier',
  message:
    'Alex, your morning momentum is outstanding today! You completed 90 minutes of algorithmic problem-solving during your peak cognitive window, and your hydration is already at 70% of goal.',
  actionableTip:
    'Before starting Linear Algebra at 1:30 PM, spend 5 minutes stretching your neck and shoulders to release desk posture stiffness. Your brain runs on glucose and oxygen!',
  balanceScore: 88,
  burnoutRisk: 'low',
  category: 'balance',
  createdAt: 'Today, 11:30 AM',
};

export const initialSquad: StudySquad = {
  id: 'sq-1',
  name: 'CS210 Algorithm Crunchers',
  courseCode: 'CS 210',
  description: 'Weekly LeetCode sprints, midterm prep, and debugging support for data structures.',
  inviteCode: 'ALGO-2026',
  members: [
    {
      id: 'mem-1',
      name: 'Alex Rivera (You)',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      role: 'member',
      statusText: 'Reviewing Dijkstra shortest paths',
      studyingNow: true,
      currentSubject: 'CS 210',
    },
    {
      id: 'mem-2',
      name: 'Maya Chen',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      role: 'lead',
      statusText: 'Writing tests for AVL tree balancing',
      studyingNow: true,
      currentSubject: 'CS 210',
    },
    {
      id: 'mem-3',
      name: 'Liam Patel',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      role: 'member',
      statusText: 'Taking a 15 min walk break',
      studyingNow: false,
    },
    {
      id: 'mem-4',
      name: 'Elena Rostova',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      role: 'member',
      statusText: 'Solving DP Knapsack variants',
      studyingNow: true,
      currentSubject: 'CS 210',
    },
  ],
  tasks: [
    {
      id: 'sqt-1',
      title: 'Compare Bellman-Ford vs Floyd-Warshall edge cases',
      assignedToName: 'Maya Chen',
      assignedToAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      dueDate: 'Tomorrow, 5:00 PM',
      status: 'in_progress',
      subject: 'CS 210',
    },
    {
      id: 'sqt-2',
      title: 'Prepare 5 graph theory mock interview questions',
      assignedToName: 'Alex Rivera',
      assignedToAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      dueDate: 'Wednesday, 2:00 PM',
      status: 'todo',
      subject: 'CS 210',
    },
    {
      id: 'sqt-3',
      title: 'Format comprehensive Big-O summary cheat sheet',
      assignedToName: 'Liam Patel',
      assignedToAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      dueDate: 'Friday, 11:00 AM',
      status: 'completed',
      subject: 'CS 210',
    },
  ],
  sessions: [
    {
      id: 'sqs-1',
      title: 'Graph Traversal & BFS/DFS Sprint Session',
      date: 'Today',
      time: '5:00 PM - 6:15 PM',
      location: 'Squad Virtual Room #2',
      attendeesCount: 4,
      isJoined: true,
      topic: 'Live coding + Whiteboard walkthroughs',
    },
    {
      id: 'sqs-2',
      title: 'Midterm Practice Exam Timed Simulation',
      date: 'Saturday, March 28',
      time: '10:00 AM - 12:00 PM',
      location: 'Engineering Library Rm 314',
      attendeesCount: 3,
      isJoined: false,
      topic: '90-minute timed mock under test conditions',
    },
  ],
  resources: [
    {
      id: 'res-1',
      title: 'CS210 Midterm Comprehensive Review Notes (PDF)',
      type: 'cheatsheet',
      addedBy: 'Maya Chen',
      downloadsCount: 18,
      sizeOrUrl: '4.2 MB PDF',
    },
    {
      id: 'res-2',
      title: 'VisualAlgo Graph Interactive Visualizer Links',
      type: 'link',
      addedBy: 'Alex Rivera',
      downloadsCount: 12,
      sizeOrUrl: 'visualgo.net/en/graphds',
    },
    {
      id: 'res-3',
      title: 'Prof. Anderson Lecture Slide Annotations: Weeks 1-6',
      type: 'notes',
      addedBy: 'Elena Rostova',
      downloadsCount: 24,
      sizeOrUrl: '8.7 MB Notes',
    },
  ],
  kudosFeed: [
    {
      id: 'kd-1',
      fromUser: 'Maya Chen',
      toUser: 'Alex Rivera',
      text: 'crushed the Dijkstra code walkthrough this morning!',
      time: '15m ago',
      likes: 3,
      emoji: '🔥',
    },
    {
      id: 'kd-2',
      fromUser: 'Liam Patel',
      toUser: 'Elena Rostova',
      text: 'shared awesome notes for the DP Knapsack problem.',
      time: '1h ago',
      likes: 4,
      emoji: '🙌',
    },
    {
      id: 'kd-3',
      fromUser: 'Elena Rostova',
      toUser: 'Maya Chen',
      text: 'thanks for organizing our Saturday timed simulation!',
      time: '3h ago',
      likes: 5,
      emoji: '⭐',
    },
  ],
  groupGoal: {
    title: 'Solve 40 Practice Problems before Midterm 1',
    targetDate: 'April 8',
    progressPercentage: 68,
  },
};
